name: the_cherry_25

services:
  web:
    image: nginx:latest
    container_name: the_cherry_25-webserver
    ports:
      - "8080:80"
    volumes:
      - ./dist:/share/webapp
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - the-cherry-25-volume:/share/data

services:
  the_cherry_25:
    image: nginx
    container_name: the_cherry_25-production
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: the_cherry_25-webapp
        target: /share/webapp

  the_cherry_25-webapp:
    name: the_cherry_25-webapp
    external: true
