services:
  web:
    image: nginx:latest
    container_name: the-cherry-25-web-server
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - the-cherry-25-volume:/usr/share/nginx/data

volumes:
  the-cherry-25-volume:
    name: the-cherry-25-volume
    external: true
