services:
  production:
    image: nginx:latest
    container_name: the-cherry-25-web-server
    ports:
      - "8080:80"
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - the-cherry-25-webapp:/share/webapp
      - the-cherry-25-volume:/share/data
  
  development:
    image: mcr.microsoft.com/devcontainers/typescript-node:latest
    container_name: the-cherry-25-devlopment
    ports:
      - "3000:3000"
    volumes:
      - the-cherry-25-volume:/workspaces/the-cherry-25/public/data

volumes:
  the-cherry-25-volume:
    name: the-cherry-25-volume
    external: true

  the-cherry-25-webapp:
    name: the-cherry-25-webapp
    external: true
