version: '3'
name: the-cherry-25

services:
    webserver:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./server.conf:/etc/nginx/conf.d/default.conf
            - the-cherry-25-data:/share/data
        restart: always

volumes:
    - the-cherry-25-data:
          name: the-cherry-25-data
          external: true
