name: the_cherry_25
services:
  node:
    image: mcr.microsoft.com/devcontainers/typescript-node:latest
    container_name: node-build
    volumes:
      - ./:/usr/src/app
      - ./dist:/usr/src/app/dist
    working_dir: /usr/src/app
    command: npm install && npm run build
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx-service
    ports:
      - "8080:80"
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/share/webapp
      - the-cherry-25-volume:/share/data

volumes:
  the-cherry-25-volume:
    name: the-cherry-25-volume