name: the-cherry-25
services:
    webapp:
        build: .
        environment:
            - NODE_ENV=production
        restart: always

    webserver:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./server.conf:/etc/nginx/conf.d/default.conf
            - ./dist:/share/webapp/dist
            - the-cherry-25-volume:/share/data
        depends_on:
            - webapp
        restart: always

volumes:
    the-cherry-25-volume:
        name: the-cherry-25-volume
        external: true
