services:
  the_cherry_25:
    image: mcr.microsoft.com/devcontainers/typescript-node:latest
    container_name: the_cherry_25-development
    ports:
      - "3000:3000"
    volumes:
      - type: volume
        source: the_cherry_25-webapp
        target: /share/webapp
      - type: volume
        source: the_cherry_25-volume
        target: /share/data

volumes:
  the_cherry_25-volume:
    name: the_cherry_25-volume
    external: true

  the_cherry_25-webapp:
    name: the_cherry_25-webapp
    external: true
